# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Philipp Hochmuth
title: Economist at the OeNB*
email: philipp.hochmuth@oenb.at
website: phhoc.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  phhoc
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: philipp-hochmuth
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: OeNB
  icon: fas fa-building
  url: https://www.oenb.at
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm an Economist in the Monetary Policy Section of the Oesterreichische Nationalbank and recently obtained my PhD from the Institute for International Economic Studies (IIES) at the Stockholm University.
  
  My research interests lie within maroeconomics and in particular consumption basket heterogeneity, nonhomothetic preferences and entrepreneurship.
  
  You can read more about me in my [<mark>CV (PDF)</mark>](/files/CV_Hochmuth.pdf){:target="_blank"}.
  
  _*Disclaimer: This is my personal website and the views expressed here do not necessarily reflect the views of the Oesterreichische Nationalbank or the Eurosystem._
  
content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: top
        #title: A Distributional Cost-of-Living Index From Aggregate Data
        description: | # this will include new lines to allow paragraphs
          #### A Distributional PCE Price Index From Aggregate Data
          Review of Income and Wealth, 2025, vol. 71(4), pp. 1–18.

          _(joint with [Markus Pettersson](www.markuspettersson.net){:target="_blank"} and Christoffer J. Weissert)_
          [<mark>Published Article (open access)</mark>](https://doi.org/10.1111/roiw.70034){:target="_blank"}
          [<mark>Working Paper (PDF)</mark>](/files/HPW_nhpce.pdf){:target="_blank"}
          [<mark>Replication package</mark>](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Froiw.70034&file=roiw70034-sup-0002-DataS2.zip){:target="_blank"}
          
          <span style="font-size:10pt">
          This article proposes a method to measure individual and aggregate changes in the cost of living when consumer behavior is nonhomothetic and microdata on consumption expenditures are not available. Aggregate prices and expenditure shares together with a single cross-sectional expenditure distribution are sufficient to create a distribution of nonhomothetic cost-of-living indices. The cost-of-living indices nest the homothetic Törnqvist price index as a limit case and only contain one unknown parameter, which is identified from macro data without aggregation bias. Using US Personal Consumption Expenditure (PCE) data, we construct nonhomothetic PCE price indices covering 71 product groups for the period 1959 to 2023. These indices reveal a 0.41 percentage point gap in annual inflation rates between the poorest and richest ten percent since 1959 and a 1.3 percentage point gap throughout 2022, thus suggesting that poorer households are hit harder both in the long run and in the recent inflation surge.
          </span>

  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: top
        #title: Distributional Consequences of Becoming Climate-Neutral
        description: | # this will include new lines to allow paragraphs
          #### Distributional Consequences of Becoming Climate-Neutral
          _(joint with [Per Krusell](http://perseus.iies.su.se/~pkrus/){:target="_blank"} and [Kurt Mitman](http://www.kurtmitman.com/){:target="_blank"})_
          [<mark>Working Paper (PDF)</mark>](/files/HKM 2025-10-17.pdf){:target="_blank"}
          
          <span style="font-size:10pt">
          The EU has embarked on an ambitious path toward climate neutrality. How difficult will this transition be for the population as a whole and different subsets of consumers? This paper investigates this question using a dynamic general equilibrium model that captures a key feature of energy consumption: the relative energy content in one's consumption basket falls significantly as a function of one's relative income. Thus, low-income consumers are expected to be hit harder by the higher energy prices that we anticipate over the next few decades. In the model, energy---a complementary input to capital and labor---can be produced either using fossil fuel or a "green" technology. We represent the EU policy in terms of a tax on fossil fuel and show that the European Commission's Fit-for-55 package implies a 106.5% tax on the fossil-based technology. The output losses from this tax are substantial, and GDP is 6.2% lower in the new steady state. The burden falls primarily on the lowest-income agent who represents the first income quintile and is 48\% more worse off than the highest-income agent representing the fifth quintile. The output losses can almost be cut in half if the economy achieves a simultaneous increase in energy efficiency as outlined in the Fit-for-55 package.
          </span>

      - layout: top
        #title: Getting Real About Wages: A Nonhomothetic Wage Deflator
        description: | # this will include new lines to allow paragraphs
          #### Getting Real About Wages: A Nonhomothetic Wage Deflator
          _(joint with [Saman Darougheh](https://www.samandarougheh.com){:target="_blank"}, [Markus Pettersson](https://www.markuspettersson.net){:target="_blank"} and [Márcia Silva-Pereira](https://www.marciasilvapereira.com){:target="_blank"})_
          [<mark>Working Paper (PDF)</mark>](/files/real_wages_draft.pdf){:target="_blank"}
          
          <span style="font-size:10pt">
          Conventional real wages---nominal wages divided by a consumption deflator---are biased from a welfare perspective when households value leisure and exhibit nonhomothetic consumption behavior. We derive a true wage deflator, shown to be a multiplicative adjustment to the consumption deflator, that can be estimated nonparametrically using cross-sectional data. Applying our framework to US data from 1984 to 2019, we find that standard measures understate real wage growth by 8–36 percent and welfare growth by 5–17 percent across the income distribution. Our deflator does not alter the compression of the wage distribution during the recent high-inflation period, however.
          </span>
          
      - layout: top
        #title: The Decline in Hours Worked of Entrepreneurs
        description: >
          #### Declining Hours Worked Among Entrepreneurs
          
          [<mark>Working Paper (PDF)</mark>](/files/JMP_Hochmuth.pdf){:target="_blank"}
          
          
          <span style="font-size:10pt">
          In this paper, I show that over the past 35 years, hours worked by entrepreneurs have fallen substantially: by five hours per week more than for workers. This decline accounts for the bulk of the fall in total hours worked and is present in all available subgroups (gender, age, education, number of children, occupation, and industry). It is robust to adjusting for compositional effects and occurs without noticeable changes in the relative hourly income of entrepreneurs. The decline originates from the top of the hours distribution: the share of entrepreneurs working more than 45 hours has dropped significantly. I interpret these facts using a Roy model of occupational choice, augmented with an intensive labor supply margin. The model allows the marginal return of working an additional hour to depend on the level of hours. I estimate the model at two points in time and find that a fall in the relative marginal return at higher hours worked is key for explaining the drop in hours and the drop in the share of entrepreneurs. I show that changes in the market structure of the goods or services that entrepreneurs sell can account for this.
          </span>
          
      - layout: top
        #title: A Nonhomothethic Price Index and Cost-of-Living Inequality
        description: | # this will include new lines to allow paragraphs
          #### A Nonhomothethic Price Index and Cost-of-Living Inequality
        
          _(joint with [Markus Pettersson](www.markuspettersson.net){:target="_blank"} and Christoffer J. Weissert)_
          [<mark>Working Paper (PDF)</mark>](/files/HPW_priceindex.pdf){:target="_blank"}
          [<mark>Online Appendix (PDF)</mark>](/files/HPW_priceindex_supplement.pdf){:target="_blank"}
          
          <span style="font-size:10pt">
          We derive a price index based on nonhomothetic preferences and use it to document cost-of-living inequality in the United States. Our framework generalizes all known superlative price indices and admits heterogeneous indices across the distribution of household consumption expenditures which aggregate consistently into welfare-relevant group indices. When necessities and luxuries are separable in the expenditure function, this generalization avoids the need to estimate a complete demand system. Using CEX-CPI data for the period 1995--2020, we find no differences in average inflation rates across the expenditure distribution, but 2.5 times higher inflation volatility for the bottom decile compared to the top decile, stemming from a larger exposure to food, gasoline, and utilities. These results contrast with the inequality found by the typical approach of constructing separate homothetic price indices for different consumer groups, and our analysis suggests that the difference follows from an income-effect bias in the homothetic group-specific indices.
          </span>

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
